blank_issues_enabled: true
contact_links:
  - name: Community support on Slack
    url: https://join.slack.com/t/aidenbyopheleon/shared_invite/zt-4apsg5d7p-FDO9ae0imxj~KgauP8lpsw
    about: Ask questions, get setup help, and share feedback with the Aiden by Opheleon community.
